DEBUG: true

COUCH_USER: "geoffreybot"
COUCH_PASSWORD: test
COUCHDB_DOMAIN: "geoffrey-db.dev"

CELERY:
  BROKER_URL: redis://localhost:6379/0
  CELERY_RESULT_BACKEND: redis://localhost:6379/1
  CELERY_TASK_SERIALIZER: json
  CELERY_ACCEPT_CONTENT:
    - json

  CELERY_RESULT_SERIALIZER: json
