API_KEY: yay
PUBLIC_KEY: ola
API_ENDPOINT: /api
DEBUG: true

COUCH_ADMIN_USER: "geoffreybot"
COUCH_ADMIN_PASSWORD: BL2")<WF{a)Q7=arAAcmS|jx.[mHD|_YK\wMChv%
COUCH_URL: "http://localhost:5984"

enabled_services: 
  - mailchimp_subscribe
  - post_new_form_data

apps:
  - mailchimp: 
    - API_KEY: 4f34ea944dd1e33a5452550789042f9c-us9
    - DATA_CENTER: us9
    - TEST_LIST_ID: f4b255a33a

CELERY:
  BROKER_URL: redis://localhost:6379/0
  CELERY_RESULT_BACKEND: redis://localhost:6379/1
  CELERY_TASK_SERIALIZER: json
  CELERY_ACCEPT_CONTENT:
    - json

  CELERY_RESULT_SERIALIZER: json
